### PR TITLE
Rebrand send screen

### LINKED ISSUE #1101: Sending ae tokens to .chain name with space
I accidentally put a space in the name and got this error:
send to wrong chain name
testnet err send to chain name

commit 6997c9b / v.0.7.1

### PR DESCRIPTION
**Pull request by etharner**
fixes #1101

### CODE REVIEW

File: src/popup/router/pages/TransferSend.vue [hunk 1]
```diff
@@ -1,178 +1,138 @@
...
+      <Button
+        data-cy="reivew-editTxDetails-button"
+        half
+        dark
+        fill="secondary"
+        @click="reviewStep = false"
+      >
+        {{
+          $t('pages.send.editTxDetails')
+        }}
```
Comment (CedrikNikita) [inline src/popup/router/pages/TransferSend.vue:126]:
```suggestion
        {{  $t('pages.send.editTxDetails')  }}
```

**Review by CedrikNikita — COMMENTED** [review]
https://github.com/aeternity/superhero-wallet/blob/a2b72739a9bfe69644d6199d399ba0745d28c55b/src/popup/router/pages/TransferSend.vue#L281
There is no variable `step` in data anymore.

**Review by CedrikNikita — COMMENTED** [review]
image
Address is getting out of the borders.

**Review by CedrikNikita — COMMENTED** [review]
image
This token doesn't have an actual value in fiat.

File: src/popup/router/components/Modals/SpendSuccess.vue [hunk 2]
```diff
@@ -0,0 +1,83 @@
...
+    @close="resolve"
+  >
+    <Pending />
+    <div>
+      <TokenAmount
+        :amount="getTxAmountTotal(transaction)"
+        :symbol="getSymbol(transaction)"
+        hide-fiat
+      />
+      {{ $t('pages.send.successalert') }}
```
Comment (CedrikNikita) [inline src/popup/router/components/Modals/SpendSuccess.vue:14]:
```suggestion
      {{ $t('pages.send.successAlert') }}
```
For now we don't have a strong opinion on that, but it should be either camelCase or kebab-case, as every other variables.

File: src/popup/locales/en.json [hunk 3]
```diff
@@ -738,15 +738,15 @@
...
       "reviewtx": "Review Transaction",
       "checkalert": "Please check the information carefully.",
       "sender": "Sending address",
       "recipient": "Receiving address",
       "amount": "Amount",
-      "editTxDetails": "Edit Transaction Details",
+      "editTxDetails": "Edit transaction",
       "tx-success": "Transaction Completed",
-      "successalert": "You have successfully sent ",
+      "successalert": "has been sent to",
```
Comment (CedrikNikita) [inline src/popup/locales/en.json:749]:
```suggestion
      "successAlert": "has been sent to",
```
For now we don't have a strong opinion on that, but it should be either camelCase or kebab-case, as every other variables.

File: src/popup/router/components/Modals/SpendSuccess.vue [hunk 4]
```diff
@@ -0,0 +1,83 @@
...
+  components: {
+    Modal, Pending, TokenAmount, Button,
+  },
+  props: {
+    resolve: { type: Function, required: true },
+    transaction: { type: Object, required: true },
+  },
+  data: () => ({
+    name: '',
+  }),
```
Comment (CedrikNikita) [inline src/popup/router/components/Modals/SpendSuccess.vue:44]:
```suggestion
```

File: src/popup/router/pages/TransferSend.vue [hunk 5]
```diff
@@ -327,7 +275,7 @@ export default {
         this.invoiceId = parsedScanResult.invoiceId;
         this.invoiceContract = parsedScanResult.invoiceContract;
 
-        this.step = 2;
+        if (await this.validate()) this.reviewStep = true;
```
Comment (CedrikNikita) [inline src/popup/router/pages/TransferSend.vue:278]:
```suggestion
        await this.validate();
```

**Review by CedrikNikita — APPROVED** [review]
