### PR TITLE
fix(notifications): use first name in the list if chainNames presented

### LINKED ISSUE #1005: Display names in notifications
names in notifications

### PR DESCRIPTION
**Pull request by etharner**
Closes #1005

### CODE REVIEW

File: src/popup/router/pages/Notifications.vue [hunk 1]
```diff
@@ -65,7 +65,8 @@ export default {
               .map((s) => s.type)
               .includes(n.type),
         )
-        .sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt));
+        .sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt))
+        .map((n) => (n.chainName ? { ...n, chainName: n.chainName?.[0] } : n));
```
Comment (davidyuk) [inline src/popup/router/pages/Notifications.vue:69]:
```suggestion
        .map((n) => (n.chainName ? { ...n, chainName: n.chainName.[0] } : n));
```
as I understand, the second check of `chainName` is an extra one, but I'm fine to merge it as it is

**Review by davidyuk — APPROVED** [review]
