### PR TITLE
Fix warnings

### LINKED ISSUE #871: Avoid console.log statements to fix the most of linter warnings
https://eslint.org/docs/rules/no-console

### PR DESCRIPTION
**Pull request by CedrikNikita**
fixes #871

### CODE REVIEW

File: src/popup/router/components/FungibleTokens/TokensListItem.vue [hunk 1]
```diff
@@ -50,8 +50,8 @@ import TokenAmount from '../TokenAmount';
 export default {
   components: { Avatar, TruncateMid, TokenAmount },
   props: {
-    tokenData: Object,
-    name: String,
+    tokenData: { type: Object, default: null },
+    name: { type: String, default: '' },
```
Comment (etharner) [inline src/popup/router/components/FungibleTokens/TokensListItem.vue:54]:
```suggestion
```
Looks like it isn't used in this component

File: src/popup/router/components/TokenAmount.vue [hunk 2]
```diff
@@ -19,11 +19,12 @@ export default {
   props: {
     amount: { type: Number, required: true },
     symbol: { type: String, default: 'AE' },
-    altText: { type: String },
+    altText: { type: String, default: '' },
     hideFiat: { type: Boolean },
     direction: {
       type: String,
       validator: (value) => ['sent', 'received'].includes(value),
+      default: 'sent',
```
Comment (etharner) [inline src/popup/router/components/TokenAmount.vue:27]: Using this approach we will have `-amount` with red color where it's not needed, for example in invite links:
image
Let's maybe introduce empty direction which will looks neutral
image

```suggestion
      validator: (value) => ['sent', 'received', ''].includes(value),
      default: '',
```

Comment (CedrikNikita) [reply src/popup/router/components/TokenAmount.vue:27]: prefer `default: undefined` in this case instead of changing validator

**Review by etharner — APPROVED** [review]
