### PR TITLE
fix(tx-details): handle overflowing tip url

### LINKED ISSUE #1261: Tipper URL is truncated on the Tx detail page.
cropped url

Also on the develop branch  commit 1732115 / v.0.8.2 
FF browser 91.0.2 (64-bit)

### PR DESCRIPTION
**Pull request by imollov**
fixes #1261

### CODE REVIEW

File: src/popup/router/pages/TransactionDetails.vue [hunk 1]
```diff
@@ -229,6 +229,17 @@ export default {
...
       }
+
+      .tip-url {
+        width: 100%;
+
+        .link-button {
+          display: block;
+          white-space: nowrap;
+          overflow: hidden;
+          text-overflow: ellipsis;
```
Comment (etharner) [inline src/popup/router/pages/TransactionDetails.vue:240]:
```suggestion
```
I suggest to review #1264 and remove this lines because we might want to have same behavior in other places.

**Comment by Liubov-crypto** [comment]
Tested, LGTM.

**Review by etharner — APPROVED** [review]
