### PR TITLE
Transactions: Load transactions only if previous are loaded

### LINKED ISSUE #537: Problem with fetching tx
> When I don't use the iframe wallet for a while, I get a problem to use my iframe wallet after a break.
> I mean I don't use the sh site for a few minutes, use other tabs, then I went back to the sh site and found this:

da75c441-d204-4b52-9e71-47223d3ab6e7

```json
{
  "id": "106",
  "appVersion": "0.3.3",
  "browser": {
    "name": "chrome",
    "version": "85.0.4183",
    "os": "Mac OS"
  },
  "error": {
    "message": "While calling getTxByAccount (account, {limit, page}), Network Error",
    "stack": "Error: While calling getTxByAccount (account, {limit, page}), Network Error\n    at e.exports (https://wallet.superhero.com/popup.js:41:620724)\n    at XMLHttpRequest.h.onerror (https://wallet.superhero.com/popup.js:41:619689)",
    "type": "unhandledrejection"
  },
  "platform": "web",
  "description": null,
  "time": "1601462124238",
  "createdAt": "2020-09-30T11:36:27.619Z",
  "updatedAt": "2020-09-30T11:36:27.619Z"
}
```

### LINKED ISSUE #579: Web wallet freezes if you do not use it for a couple of minutes
I haven't used the wallet for a couple of minutes, when I returned to it I got this error.

1. Go to https://release-0-4-0.wallet.z52da5wt.xyz/
2. Click on Create new wallet
3. Leave for a while
4. See an error:

Знімок екрана 2020-11-04 о 12 01 50 пп

Also, there was a problem with sending a report through the wallet:
Знімок екрана 2020-11-04 о 12 04 03 пп

Browser: chrome, Version 86.0.4240 (Mac OS)
OS: 10.15.7

### PR DESCRIPTION
**Pull request by CedrikNikita**
fixes #579,
fixes #537,
part of #710

### CODE REVIEW

File: src/popup/router/pages/Transactions.vue [hunk 1]
```diff
@@ -103,12 +103,15 @@ export default {
...
     async getLatest() {
+      if (this.loading) return;
+      this.loading = true;
       const transactions = await this.$store.dispatch('fetchTransactions', {
         limit: 10,
         page: 1,
         recent: true,
       });
       this.updateTransactions(transactions);
+      this.loading = false;
```
Comment (davidyuk) [inline src/popup/router/pages/Transactions.vue:114]: Would be more accurate to wrap it into `try`/`finally` to avoid freezing the loading state if the request got failed for some reason.

**Review by davidyuk — APPROVED** [review]

**Review by mradkov — APPROVED** [review]

**Review by davidyuk — APPROVED** [review]
