### PR TITLE
Fix logout/login related issues

### LINKED ISSUE #523: New wallet generation process hung after deleting an existing account
The wallet hung and did not allow me to create a new account after I left the old one.

Extension on Chrome, Firefox. 

Steps to reproduce the behaviour:
1. Log out from extension.
2. Open extension
3. Click on 'I agree"
4. Click on Generate new wallet
5. Click on Proceed to your wallet
6. See an error on Pop-up:

Знімок екрана 2020-09-18 о 7 50 13 пп

 - OS:  iOS
 - Browser: chrome, firefox
 - Version: 0.3.3

### PR DESCRIPTION
**Pull request by CedrikNikita**
first commit fixes `Error: Attempting to use a disconnected port object`,
second fixes #523

### CODE REVIEW

File: src/lib/rpcWallet.js [hunk 1]
```diff
@@ -307,10 +307,12 @@ export default {
   async [AEX2_METHODS.LOGOUT]() {
     const { clients: aepps } = this.sdk.getClients();
     Array.from(aepps.values()).forEach(aepp => {
-      aepp.sendMessage(
-        { method: 'connection.close', params: { reason: 'bye' }, jsonrpc: '2.0' },
-        true,
-      );
+      if (aepp.info.status !== 'DISCONNECTED') {
```
Comment (mradkov) [inline src/lib/rpcWallet.js:310]: In this case, we are sending `connection.close` if the status **is not** `DISCONNECTED`. Is that the desired logic?

Comment (CedrikNikita) [reply src/lib/rpcWallet.js:310]: yes

**Review by mradkov — APPROVED** [review]
