### PR TITLE
fix(recent-txs): align empty and loading states

### LINKED ISSUE #1084: Misaligned recent txs loading and empty state
Screenshot 2021-05-18 at 10 20 47
Screenshot 2021-05-18 at 10 25 41

### PR DESCRIPTION
**Pull request by imollov**
fixes #1084

| before | after |
| -------- | -------------- | 
| recording (18) | recording (17) |

### CODE REVIEW

File: src/popup/router/components/RecentTransactions.vue [hunk 1]
```diff
@@ -147,7 +147,7 @@ export default {
   .message,
   .spinner {
     min-height: 174px;
-    padding-bottom: 8px;
+    padding-bottom: 48px;
     flex-grow: 1;
     display: flex;
     align-items: center;
```
Comment (etharner) [inline src/popup/router/components/RecentTransactions.vue:153]: I still have misaligned `spinner` and `message` in desktop version
image
After removing this styles
```suggestion
```
`message` and `spinner` are aligned on the top which is looks nice everywhere for me:
image
Maybe let's fix this way?

Comment (imollov) [reply src/popup/router/components/RecentTransactions.vue]: I've re-implemented it as per figma designs where elements are centered. It works on all platforms now.

Comment (imollov) [reply src/popup/router/components/RecentTransactions.vue]: Screenshot 2021-05-20 at 14 30 00

**Review by etharner — APPROVED** [review]
