### PR TITLE
Simplify resetting by reloading page after that

### LINKED ISSUE #624: An error after deleting account
The error appears after I delete my account: 
2020-11-19 11 34 42 дп

An error when I submit a bug report to the wallet:
2020-11-19 11 34 48 дп

Superhero 366bffd/v.0.4.2 for Android

### PR DESCRIPTION
**Pull request by davidyuk**
fixes #624 

This approach we have been used in the Base aepp.

Pros:
- the most robust approach
- no need to test all new features against resetting (to make a correct resetting without reloading requires more accurate state handling)
- simplifies testing because not needed to use other tools (reinstall extension, incognito mode, android app settings) to completely reset the app state
- probably is more secure because all data is explicitly deleted and the app is restarted, so less probable to have something cached from the previous account

Cons:
- resettings happen slower because of page reload (shouldn't be critical because resetting assumed to be an edge case for the end user)

### CODE REVIEW

**Review by CedrikNikita — APPROVED** [review]
@davidyuk look at lgtb bot report. All the rest changes look good, actually this changes may close #560, #570 issues.

File: src/lib/rpcWallet.js [hunk 1]
```diff
@@ -291,8 +291,6 @@ export default {
       browser.tabs.reload(aepp.connection.port.sender.tab.id);
       this.sdk.removeRpcClient(aepp.id);
     });
-    delete walletController.wallet;
-    this.initFields();
   },
   async [AEX2_METHODS.INIT_RPC_WALLET]({ address, network }) {
```
Comment (mradkov) [inline src/lib/rpcWallet.js:295]: Can we have a consistent function naming convention in this file?  Quoting this change: `async [AEX2_METHODS.LOGOUT]()` -> `async disconnect()`

Comment (davidyuk) [reply src/lib/rpcWallet.js:295]: I assuming `AEX2_METHODS` a deprecated object (mainly because it is not connected to AEX2, but message exchanging between background and popup) and planning to get rid of it in future PRs.

**Review by mradkov — APPROVED** [review]
Code changes look good.

**Review by Liubov-crypto — COMMENTED** [review]
Logging into wallets after deleting an existing account and login in a new work smoothly. 

Found several bugs that this PR does not fix - synchronization of the wallet and superhero UI.
Does not upload user avatar and information to Superhero UI. Some data from my profile has disappeared. The avatar also disappeared from the wallet, although it was there before.

не загрузил аватар пользователя в брейв
пропала инфа и аватар пользователя
пропал аватар

I need to reload the page several times for an avatar and a photo on the cover to appear (there is no bio and location)
not sync info between sh UI and sh wallet

In the brave browser instead of the equivalent in currency, the wallet shows zeros:
нулевые суммы в брейв

**Comment by Liubov-crypto** [comment]
Web wallet:
Send tip - pass
Claim tip-  was successful but the amount didn’t appear in my wallet
Activity - pass
Invite - pass
Withdraw - pass
Top up - pass
Names - pass

FF/Сhrome extension: 
Send tip- pass 
Claim tip- was successful but the amount didn’t appear in my wallet
Send tip via Twitter/Youtube button -passed, but the transaction is marked as pending in my wallet / from Twitter was successful.
Activity - pass
Top up -pass
Invite - pass
Withdraw - pass
Names - pass
