### PR TITLE
logger: Fix handling vue errors

### LINKED ISSUE #437: Logger ignores exceptions shown in vue event handlers
Check this reproduction: 8365df63bed7c04849f324a9ec282a8f8db76752

https://reproduction-logger.wallet.z52da5wt.xyz/

I assume that the button on click should show a modal proposing to send the exception to us.

### PR DESCRIPTION
**Pull request by CedrikNikita**
fixes #437

### CODE REVIEW

**Review by davidyuk — COMMENTED** [review]
I meant that an exception in vue handler should show a modal proposing to send the exception, it doesn't look like that you have fixed it in this PR. Please check the reproduction 5dd1a6ce1f59a5592c6f9c8c5ea73abd5e883881.

File: src/lib/logger.js [hunk 1]
```diff
@@ -14,8 +14,7 @@ export default class Logger {
       Vue.config.errorHandler = (error, vm, info) => {
         console.error(info);
         console.error(error);
-        Object.assign(error, { info, type: 'vue-error' });
-        Logger.write(error);
+        Logger.write({ message: error.toString(), info, type: 'vue-error' });
```
Comment (davidyuk) [inline src/lib/logger.js:17]: Ok, I got how it works:
https://github.com/aeternity/superhero-wallet/blob/a43d7bec1e14801b9cf0e8741e1d195e5893c2ff/src/lib/logger.js#L73

**Review by davidyuk — APPROVED** [review]

**Review by mradkov — APPROVED** [review]
