### PR TITLE
TransactionFilters: Fix positioning

### LINKED ISSUE #190: Activity History iOS: Sticky header overlaps with main header
| Scrolled up | When scrolling |
|---|---|
| IMG_1795 | IMG_1794 |

### PR DESCRIPTION
**Pull request by davidyuk**
fixes #190

### CODE REVIEW

File: src/popup/App.vue [hunk 1]
```diff
@@ -139,6 +139,7 @@ export default {
   position: relative;
   min-height: 600px;
   margin: 0 auto;
+  overflow: visible !important;
```
Comment (davidyuk) [inline src/popup/App.vue:142]: https://stackoverflow.com/a/47878455/6176994
