### PR TITLE
bugfix: handle blur on custom field from vee-validate

### LINKED ISSUE #3542: Missing 'This field is required.' msg when unfocusing the recipient field
**Describe the bug**
The user is not informed that the Recioient field has been left blank.

**To Reproduce**
1. Go to Send modal
2. Click in Recipient field
3. Click in Amount field
4. See missing message under Recipient field ' This field is required.'

**Screenshots**

https://github.com/user-attachments/assets/0802fecc-d08b-4a60-9127-888d0d1fcb49

### PR DESCRIPTION
**Pull request by alex-k8**
closes #3542

### CODE REVIEW

File: src/popup/components/form/FormTextarea.vue [hunk 1]
```diff
@@ -22,7 +22,10 @@
         :disabled="readonly"
         @keydown.enter.prevent="handleEnterClick"
         @input="(payload) => handleInput(payload as InputEvent)"
-        @blur="(payload) => handleInput(payload as unknown as InputEvent)"
```
Comment (CedrikNikita) [inline src/popup/components/form/FormTextarea.vue:25]: I suggest to add `handleBlur` method and not make template more complex.

**Comment by dvdbak** [comment]
LGTM

**Review by CedrikNikita — APPROVED** [review]
